name: Gold Price Scraper

on:
  schedule:
    - cron: "30 5 * * 1-5" # Runs at 11:00 AM IST (5:30 AM UTC)
  workflow_dispatch: # Allows manual execution

jobs:
  update_gold_price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests pdfplumber

      - name: Fetch yesterday’s PDF from GitHub
        run: |
          mkdir -p data
          if [ -f "data/today.pdf" ]; then
            mv data/today.pdf data/yesterday.pdf
          fi

      - name: Run Gold Price Script
        run: python compare.py # Ensure your script saves the PDF as `data/today.pdf`

      - name: Commit and Push New PDF
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/today.pdf data/yesterday.pdf
          git commit -m "Updated gold price PDF for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
